#!/bin/bash

# Update package lists and install Nginx
apt-get -y update
apt-get -y install nginx

# Create default HTML files
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Modify Nginx configurations
sed -i '/server_name _;/a \\\trewrite ^\/redirect_me https:\/\/github.com\/linda-murei05 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

echo -e "\tadd_header X-Served-By $(hostname);" >> /etc/nginx/nginx.conf

# Restart Nginx service
service nginx restart

